services:
  jupyterlab:
    image: oliverchenbz/datapipeline
    ports:
      - "8888:8888"
    env_file:
      - .env
    volumes:
      - ./:/datapipeline
    networks:
      - dbnetwork
  postgres:
    image: postgres:latest   
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - datapipelinepostgresdata:/var/lib/postgresql/data
    networks:
      - dbnetwork
  mongo:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - datapipelinemongodata:/data/db
    networks:
      - dbnetwork

volumes:
  datapipelinepostgresdata:
  datapipelinemongodata:

networks:
  dbnetwork:
